### PR TITLE
Fix No such index: 'sort_on' warnings

### PR DESCRIPTION
**Pull request by davisagli**
Fixes a regression introduced in https://github.com/plone/plone.restapi/pull/1533

### CODE REVIEW

**Review by ksuess — APPROVED** [review]

**Review by erral — APPROVED** [review]

**Review by wesleybl — APPROVED** [review]
LGTM. But since the test didn't catch that, I think a test for that should be added. The log should be tested after instantiating an object of the ZCatalogCompatibleQueryAdapter class. The log cannot contain `sort_on` or `sort_order`, if these parameters are passed in the query.

**Comment by wesleybl** [comment]
I added the test.

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
hmm failed for Python < 3.10:

`AttributeError: 'TestSearchFunctional' object has no attribute 'assertNoLogs'`

It looks like `assertNoLogs` is only for Python >= 3.10. Should we put a condition on the test?

**Comment by davisagli** [comment]
@wesleybl Sure, that's probably good enough.

Thanks for working on the test, and sorry I lost track of this during the holidays.

**Comment by wesleybl** [comment]
@davisagli I skip test in Python < 3.10

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs
